### ISSUE TITLE
Something is error

### ISSUE THREAD

**Issue by rechie1995** [Sanva/facedetect#1]
![image](https://cloud.githubusercontent.com/assets/11208036/22637952/0bb7a72c-ec80-11e6-96c2-f7c00f047b67.png)  
My OpenCV version is 3.2.  
And my Compiler is g++ 6.2.0  
But Something is error.
Could you help me please ?

**Comment by Sanva** [comment]
Hi @rechie1995 ,

Could you be more specific? I mean, what command are you using to try to compile? From your screenshot I can see the errors, but not the command used to try to compile.
